### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by Zoxouu** [scharez/ptero-directus-egg#1]
```
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Status: Image is up to date for ghcr.io/parkervcp/yolks:nodejs_21 
Digest: sha256:dc65a2e2995904124ed26d4d54501af6bfacf93a3b8e445cd4dff94f66dd9d85 
[Pterodactyl Daemon]: Finished pulling Docker container image
v21.7.3
:/home/container$ ${STARTUP_COMMAND}
Installing directus...
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: rollup-plugin-styles@4.0.0
npm warn Found: rollup@3.29.4
npm warn node_modules/@directus/extensions-sdk/node_modules/rollup
npm warn   rollup@"3.29.4" from @directus/extensions-sdk@12.1.3
npm warn   node_modules/@directus/extensions-sdk
npm warn     @directus/extensions-sdk@"12.1.3" from @directus/api@23.1.3
npm warn     node_modules/@directus/api
npm warn   1 more (rollup-plugin-esbuild)
npm warn
npm warn Could not resolve dependency:
npm warn peer rollup@"^2.63.0" from rollup-plugin-styles@4.0.0
npm warn node_modules/@directus/extensions-sdk/node_modules/rollup-plugin-styles
npm warn   rollup-plugin-styles@"4.0.0" from @directus/extensions-sdk@12.1.3
npm warn   node_modules/@directus/extensions-sdk
npm warn
npm warn Conflicting peer dependency: rollup@2.79.2
npm warn node_modules/rollup
npm warn   peer rollup@"^2.63.0" from rollup-plugin-styles@4.0.0
npm warn   node_modules/@directus/extensions-sdk/node_modules/rollup-plugin-styles
npm warn     rollup-plugin-styles@"4.0.0" from @directus/extensions-sdk@12.1.3
npm warn     node_modules/@directus/extensions-sdk

up to date, audited 1103 packages in 1s

194 packages are looking for funding
  run `npm fund` for details

9 vulnerabilities (4 low, 1 moderate, 4 high)
To address issues that do not require attention, run:
  npm audit fix
To address all issues (including breaking changes), run:
  npm audit fix --force
Run `npm audit` for details.

> directus@1.0.0 bootstrap
> npx directus bootstrap
node:internal/modules/cjs/loader:1142
  const err = new Error(message);
              ^
Error: Cannot find module './out/isolated_vm'
Require stack:
- /home/container/node_modules/isolated-vm/isolated-vm.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
    at Module._load (node:internal/modules/cjs/loader:983:27)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/container/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at cjsLoader (node:internal/modules/esm/translators:366:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/container/node_modules/isolated-vm/isolated-vm.js' ]
}
Node.js v21.7.3

> directus@1.0.0 db-migrate-latest
> npx directus database migrate:latest
node:internal/modules/cjs/loader:1142
  const err = new Error(message);
              ^
Error: Cannot find module './out/isolated_vm'
Require stack:
- /home/container/node_modules/isolated-vm/isolated-vm.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
    at Module._load (node:internal/modules/cjs/loader:983:27)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/container/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at cjsLoader (node:internal/modules/esm/translators:366:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/container/node_modules/isolated-vm/isolated-vm.js' ]
}
Node.js v21.7.3
Starting directus...
> directus@1.0.0 start
> npx directus start
node:internal/modules/cjs/loader:1142
  const err = new Error(message);
              ^
Error: Cannot find module './out/isolated_vm'
Require stack:
- /home/container/node_modules/isolated-vm/isolated-vm.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
    at Module._load (node:internal/modules/cjs/loader:983:27)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/container/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at cjsLoader (node:internal/modules/esm/translators:366:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/container/node_modules/isolated-vm/isolated-vm.js' ]
}
Node.js v21.7.3
Directus successfully started
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 0
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Status: Image is up to date for ghcr.io/parkervcp/yolks:nodejs_21 
Digest: sha256:dc65a2e2995904124ed26d4d54501af6bfacf93a3b8e445cd4dff94f66dd9d85 
[Pterodactyl Daemon]: Finished pulling Docker container image
v21.7.3
:/home/container$ ${STARTUP_COMMAND}
Installing directus...
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: rollup-plugin-styles@4.0.0
npm warn Found: rollup@3.29.4
npm warn node_modules/@directus/extensions-sdk/node_modules/rollup
npm warn   rollup@"3.29.4" from @directus/extensions-sdk@12.1.3
npm warn   node_modules/@directus/extensions-sdk
npm warn     @directus/extensions-sdk@"12.1.3" from @directus/api@23.1.3
npm warn     node_modules/@directus/api
npm warn   1 more (rollup-plugin-esbuild)
npm warn
npm warn Could not resolve dependency:
npm warn peer rollup@"^2.63.0" from rollup-plugin-styles@4.0.0
npm warn node_modules/@directus/extensions-sdk/node_modules/rollup-plugin-styles
npm warn   rollup-plugin-styles@"4.0.0" from @directus/extensions-sdk@12.1.3
npm warn   node_modules/@directus/extensions-sdk
npm warn
npm warn Conflicting peer dependency: rollup@2.79.2
npm warn node_modules/rollup
npm warn   peer rollup@"^2.63.0" from rollup-plugin-styles@4.0.0
npm warn   node_modules/@directus/extensions-sdk/node_modules/rollup-plugin-styles
npm warn     rollup-plugin-styles@"4.0.0" from @directus/extensions-sdk@12.1.3
npm warn     node_modules/@directus/extensions-sdk

up to date, audited 1103 packages in 1s

194 packages are looking for funding
  run `npm fund` for details

9 vulnerabilities (4 low, 1 moderate, 4 high)
To address issues that do not require attention, run:
  npm audit fix
To address all issues (including breaking changes), run:
  npm audit fix --force
Run `npm audit` for details.

> directus@1.0.0 bootstrap
> npx directus bootstrap
node:internal/modules/cjs/loader:1142
  const err = new Error(message);
              ^
Error: Cannot find module './out/isolated_vm'
Require stack:
- /home/container/node_modules/isolated-vm/isolated-vm.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
    at Module._load (node:internal/modules/cjs/loader:983:27)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/container/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at cjsLoader (node:internal/modules/esm/translators:366:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/container/node_modules/isolated-vm/isolated-vm.js' ]
}
Node.js v21.7.3

> directus@1.0.0 db-migrate-latest
> npx directus database migrate:latest
node:internal/modules/cjs/loader:1142
  const err = new Error(message);
              ^
Error: Cannot find module './out/isolated_vm'
Require stack:
- /home/container/node_modules/isolated-vm/isolated-vm.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
    at Module._load (node:internal/modules/cjs/loader:983:27)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/container/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at cjsLoader (node:internal/modules/esm/translators:366:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/container/node_modules/isolated-vm/isolated-vm.js' ]
}
Node.js v21.7.3
Starting directus...
> directus@1.0.0 start
> npx directus start
node:internal/modules/cjs/loader:1142
  const err = new Error(message);
              ^
Error: Cannot find module './out/isolated_vm'
Require stack:
- /home/container/node_modules/isolated-vm/isolated-vm.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
    at Module._load (node:internal/modules/cjs/loader:983:27)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/container/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at cjsLoader (node:internal/modules/esm/translators:366:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/container/node_modules/isolated-vm/isolated-vm.js' ]
}
Node.js v21.7.3
Directus successfully started
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 0
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
```

**Comment by scharez** [comment]
Hi, could you try using the nodejs version 20 docker image in the startup settings?

![grafik](https://github.com/user-attachments/assets/86eb8220-a353-4305-b3de-b33131d00e33)

**Comment by Zoxouu** [comment]
I tested with all versions

**Comment by scharez** [comment]
Which directus version are you running?
